const path = {
  HOME: "/home",
  SIGN_IN: "/",
  LOG_IN: "/log-in",
  SIGN_UP: "/signup",
  MANAGER_USER: "manage-user",
  MANAGER_STORE: "manage-store",
  CREATE_STORE: "create-store",
  CREATE_USER: "create-user",
  CREATE_SOLUTION: "create-solution",
  CREATE_RESULT: "create-result",
  CREATE_MACHINE: "create-machine",
  MANAGER_SOLUTION: "manage-solution",
  MANAGER_RESULT: "manage-result",
  MANAGER_MACHINE: "manage-machine",
  MANAGER_PROBLEM: "manage-problem",
  CREATE_PROBLEM: "create-problem",
  DASH_BOARD: "dash-board",
  OVERALL_TRANSACTION: "overall-transaction",
  DASH_BOARD_TRANSFER: "dash-board-transfer",
  ANALYSIS_RECORD_WITH_TYPE_RESULT: "analysis-record-with-type-result",
  UPLOAD_RECORD_SUCCESS: "/upload-record-success",
  MANAGER_SOLUTION_REQUEST: "manage-solution-request",
  UPLOAD_RECORD_FAILURE: "/upload-record-failure",
  MANAGER_RECORD_TRANSACTION: "manage-record-transaction",
  ADMIN: "/admin",
  SCHEDULE_MANAGE: "schedule-manage",
  SCHEDULE: "schedule",
  SCHEDULE_CREATE: "schedule-create",
  HISTORY: "history",
  HISTORY_MANAGE: "history-manage",
  HISTORY_MANAGE_TEACHER: "history-manage-teacher",
  LAB: "lab",
  LAB_MANAGE: "/admin/lab-manage",
};

export default path;
